issuer: https://dex:5556/dex
web:
  https: 0.0.0.0:5556
  tlsCert: /certs/dex.pem
  tlsKey: /certs/dex.pem
storage:
  type: sqlite3
  config:
    file: /data/dex.db
staticClients:
  - id: kcp-dev
    public: true
    redirectURIs:
      - http://localhost:8000 # oidc-login callback url
      - https://127.0.0.1:8080/callback # kube-bind callback url
      - https://127.0.0.1:6443/callback # kube-bind callback url
      - https://localhost:6444/callback # kube-bind callback url
    name: 'KCP App'
    secret: "Z2Fyc2lha2FsYmlzdmFuZGVuekWplCg=="

# Enable password authentication
enablePasswordDB: true

# Static user passwords
staticPasswords:
  - email: "admin@example.com"
    # bcrypt hash of the string "password": $2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W
    hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
    username: "admin"
    userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
    groups:
      - "system:kcp:admin"
      - "system:admin"