# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# CodeRabbit Configuration Template
# Complete reference: https://docs.coderabbit.ai/reference/configuration
# Copy this file to .coderabbit.yaml in your repository root

# =============================================================================
# GLOBAL SETTINGS
# These settings apply to your entire CodeRabbit configuration
# =============================================================================

# Set the language for reviews by using the corresponding ISO language code.
# Options: de, de-DE, de-AT, de-CH, en, en-US, en-AU, en-GB, en-CA, en-NZ, en-ZA, es, es-AR, fr, fr-CA, fr-CH, fr-BE, nl, nl-BE, pt-AO, pt, pt-BR, pt-MZ, pt-PT, ar, ast-ES, ast, be-BY, be, br-FR, br, ca-ES, ca, ca-ES-valencia, ca-ES-balear, da-DK, da, de-DE-x-simple-language, el-GR, el, eo, fa, ga-IE, ga, gl-ES, gl, it, ja-JP, ja, km-KH, km, ko-KR, ko, pl-PL, pl, ro-RO, ro, ru-RU, ru, sk-SK, sk, sl-SI, sl, sv, ta-IN, ta, tl-PH, tl, tr, uk-UA, uk, zh-CN, zh, crh-UA, crh, cs-CZ, cs, nb, no, nl-NL, de-DE-x-simple-language-DE, es-ES, it-IT, fa-IR, sv-SE, de-LU, fr-FR, bg-BG, bg, he-IL, he, hi-IN, hi, vi-VN, vi, th-TH, th, bn-BD, bn
# Default: "en-US"
language: "en-US"

# Set the tone of reviews and chat. Example: 'You must use talk like Mr. T. I pity the fool who doesn't!'
# Default: ""
tone_instructions: "be professional and concise, avoid humor, no familiar language"
early_access: false
enable_free_tier: true

chat:
  art: false
  auto_reply: true

reviews:
  profile: "chill"

  # This lets coderabbit its status as a workflow check on the PR, while
  # it is making a review the status is pending. Otherwise it will be
  # green (or red if something catastrophically fails).
  commit_status: true

  # If enabled and coderabbit encounters an error during review, it will
  # set the commit status to failed, preventing e.g. merging.
  fail_commit_status: false

  # This causes coderabbit to edit the PR description with a summary of
  # changes. Can be noisy and is often wrong in big PRs.
  high_level_summary: false

  # With this enabled coderabbit makes a comment on every PR (with or
  # without the label) and updates it with the status.
  # OK-ish on PRs it reviews but noisy on others.
  # This comment also contains the "walkthrough" mentioned in other
  # settings.
  review_status: false

  # Stop the review if the PR is closed while the review is in progress.
  abort_on_close: true

  # Let coderabbit approve a PR if there are no issues found.
  request_changes_workflow: true

  # If enabled coderabbit will apply labels to the PR based on its
  # analysis. Can be noisy. And wrong.
  auto_apply_labels: false

  # If enabled coderabbit assigns reviewers based on who edited files
  # recently. Generally this should be resolved by code ownership.
  auto_assign_reviewers: false

  # Disabling general fluff. Each of these can be request individually
  # with a command.
  collapse_walkthrough: false
  changed_files_summary: false
  sequence_diagrams: false
  high_level_summary_in_walkthrough: false
  estimate_code_review_effort: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  poem: false
  in_progress_fortune: false
  finishing_touches:
    docstrings:
      enabled: False
    unit_tests:
      enabled: False
  pre_merge_checks:
    docstrings:
      mode: off
    title:
      mode: off
    description:
      mode: off
    issue_assessment:
      mode: off

  # Specify file patterns to include or exclude in a review using glob patterns (e.g., !dist/**, src/**). These patterns also apply to 'git sparse-checkout', including specified patterns and ignoring excluded ones (starting with '!') when cloning the repository.
  # Default: []
  path_filters: [
    # ignore generated files
    '!**/*_generated.*',
    '!sdk/client/**',
    # ignore generated yaml (e.g. crd) files
    '!**/*.yaml',
    # allow inspecting examples
    '**/examples/*.yaml'
  ]

  # Configuration for auto review
  # Default: {}
  auto_review:
    # List of labels to control which PRs/MRs to review. Labels starting with '!' are negative matches. Examples: ['bug', 'feature'] - reviews PRs with 'bug' OR 'feature' label. ['!wip'] - reviews all PRs except those with 'wip' label. ['bug', '!wip'] - reviews PRs with 'bug' label but not if they have 'wip' label.
    # Default: []
    labels: [
      "ai-code-review",
    ]
