version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - misspell
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
  settings:
    nolintlint:
      require-specific: true
      allow-unused: false
    revive:
      confidence: 0.6
      rules:
        - name: context-keys-type
        - name: duplicated-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: errorf
        - name: superfluous-else
        - name: unreachable-code
        - name: bool-literal-in-expr
        - name: constant-logical-expr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - goconst
        path: (.+)_test\.go
      - linters:
          - staticcheck
        text: QF1008
    paths:
      - pkg/client
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kube-bind)
        - prefix(github.com/kube-bind/sdk)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - pkg/client
      - third_party$
      - builtin$
      - examples$
