builds:
- id: "kubectl-bind"
  main: ./cmd/kubectl-bind
  binary: bin/kubectl-bind
  ldflags:
  - "{{ .Env.LDFLAGS }}"
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  - ppc64le
  ignore:
  - goos: darwin
    goarch: ppc64le
  - goos: windows
    goarch: ppc64le
archives:
- id: kubectl-bind
  builds:
  - kubectl-bind
  name_template: "kubectl-bind_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  prerelease: auto
  mode: keep-existing

krews:
- name: bind
  ids:
  - kubectl-bind
  index:
    owner: kube-bind
    name: krew-index
    token: "{{ .Env.KREW_GITHUB_TOKEN }}"
  homepage: "https://kubectl-bind.io/"
  description: |
    Binds API services and other remote types into the current cluster. API services
    are CRDs that are operated by a service provider without anything by that service
    provider running in the local cluster. Real SaaS for Kubernetes.
  short_description: "Bind API services and other remote types into the current cluster."
  skip_upload: auto
