baseImageOverrides:
  github.com/google/ko: golang:1.23.4

builds:
- id: konnector
  dir: ./cmd/konnector
  ldflags:
  - "{{ .Env.LDFLAGS }}"
- id: example-backend
  dir: ./cmd/example-backend
  ldflags:
  - "{{ .Env.LDFLAGS }}"
- id: example-backend-kcp
  dir: ./contrib/example-backend-kcp/cmd/backend
  ldflags:
  - "{{ .Env.LDFLAGS }}"
