baseImageOverrides:
  github.com/google/ko: golang:1.19

builds:
- id: konnector
  dir: ./cmd/konnector
  ldflags:
  - "{{ .Env.LDFLAGS }}"
- id: example-backend
  dir: ./cmd/example-backend
  ldflags:
  - "{{ .Env.LDFLAGS }}"