baseImageOverrides:
  github.com/google/ko: golang:1.24.0

builds:
- id: konnector
  dir: ./cmd/konnector
  ldflags:
  - "{{ .Env.LDFLAGS }}"
- id: backend
  dir: ./cmd/backend
  ldflags:
  - "{{ .Env.LDFLAGS }}"
