/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/


//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"
	"context"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	kubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha1"


	kubebindv1alpha1client "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha1"
)

// ClusterBindingsClusterGetter has a method to return a ClusterBindingClusterInterface.
// A group's cluster client should implement this interface.
type ClusterBindingsClusterGetter interface {
	ClusterBindings() ClusterBindingClusterInterface
}

// ClusterBindingClusterInterface can operate on ClusterBindings across all clusters,
// or scope down to one cluster and return a ClusterBindingsNamespacer.
type ClusterBindingClusterInterface interface {
	Cluster(logicalcluster.Path) ClusterBindingsNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*kubebindv1alpha1.ClusterBindingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type clusterBindingsClusterInterface struct {
	clientCache kcpclient.Cache[*kubebindv1alpha1client.KubeBindV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *clusterBindingsClusterInterface) Cluster(clusterPath logicalcluster.Path) ClusterBindingsNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &clusterBindingsNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}


// List returns the entire collection of all ClusterBindings across all clusters. 
func (c *clusterBindingsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*kubebindv1alpha1.ClusterBindingList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterBindings(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all ClusterBindings across all clusters.
func (c *clusterBindingsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterBindings(metav1.NamespaceAll).Watch(ctx, opts)
}
// ClusterBindingsNamespacer can scope to objects within a namespace, returning a kubebindv1alpha1client.ClusterBindingInterface.
type ClusterBindingsNamespacer interface {
	Namespace(string) kubebindv1alpha1client.ClusterBindingInterface
}

type clusterBindingsNamespacer struct {
	clientCache kcpclient.Cache[*kubebindv1alpha1client.KubeBindV1alpha1Client]
	clusterPath logicalcluster.Path
}

func (n *clusterBindingsNamespacer) Namespace(namespace string) kubebindv1alpha1client.ClusterBindingInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).ClusterBindings(namespace)
}
