/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	logicalcluster "github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apiskubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha1"
	versioned "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned"
	internalinterfaces "github.com/kube-bind/kube-bind/sdk/kcp/informers/externalversions/internalinterfaces"
	kubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/kcp/listers/kubebind/v1alpha1"
)

// ClusterBindingClusterInformer provides access to a shared informer and lister for
// ClusterBindings.
type ClusterBindingClusterInformer interface {
	Cluster(logicalcluster.Name) ClusterBindingInformer
	ClusterWithContext(context.Context, logicalcluster.Name) ClusterBindingInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kubebindv1alpha1.ClusterBindingClusterLister
}

type clusterBindingClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewClusterBindingClusterInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBindingClusterInformer(client versioned.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredClusterBindingClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredClusterBindingClusterInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBindingClusterInformer(client versioned.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha1().ClusterBindings().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha1().ClusterBindings().Watch(context.Background(), options)
			},
		},
		&apiskubebindv1alpha1.ClusterBinding{},
		resyncPeriod,
		indexers,
	)
}

func (i *clusterBindingClusterInformer) defaultInformer(client versioned.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredClusterBindingClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,
	}, i.tweakListOptions)
}

func (i *clusterBindingClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return i.factory.InformerFor(&apiskubebindv1alpha1.ClusterBinding{}, i.defaultInformer)
}

func (i *clusterBindingClusterInformer) Lister() kubebindv1alpha1.ClusterBindingClusterLister {
	return kubebindv1alpha1.NewClusterBindingClusterLister(i.Informer().GetIndexer())
}

func (i *clusterBindingClusterInformer) Cluster(clusterName logicalcluster.Name) ClusterBindingInformer {
	return &clusterBindingInformer{
		informer: i.Informer().Cluster(clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

func (i *clusterBindingClusterInformer) ClusterWithContext(ctx context.Context, clusterName logicalcluster.Name) ClusterBindingInformer {
	return &clusterBindingInformer{
		informer: i.Informer().ClusterWithContext(ctx, clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

type clusterBindingInformer struct {
	informer cache.SharedIndexInformer
	lister   kubebindv1alpha1.ClusterBindingLister
}

func (i *clusterBindingInformer) Informer() cache.SharedIndexInformer {
	return i.informer
}

func (i *clusterBindingInformer) Lister() kubebindv1alpha1.ClusterBindingLister {
	return i.lister
}

// ClusterBindingInformer provides access to a shared informer and lister for
// ClusterBindings.
type ClusterBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kubebindv1alpha1.ClusterBindingLister
}

type clusterBindingScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterBindingInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterBindingInformer(client versioned.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterBindingInformer(client, resyncPeriod, namespace, indexers, nil)
}

// NewFilteredClusterBindingInformer constructs a new informer for ClusterBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterBindingInformer(client versioned.Interface, resyncPeriod time.Duration, namespace string, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha1().ClusterBindings(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha1().ClusterBindings(namespace).Watch(context.Background(), options)
			},
		},
		&apiskubebindv1alpha1.ClusterBinding{},
		resyncPeriod,
		indexers,
	)
}

func (i *clusterBindingScopedInformer) Informer() cache.SharedIndexInformer {
	return i.factory.InformerFor(&apiskubebindv1alpha1.ClusterBinding{}, i.defaultInformer)
}

func (i *clusterBindingScopedInformer) Lister() kubebindv1alpha1.ClusterBindingLister {
	return kubebindv1alpha1.NewClusterBindingLister(i.Informer().GetIndexer())
}

func (i *clusterBindingScopedInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterBindingInformer(client, resyncPeriod, i.namespace, cache.Indexers{
		cache.NamespaceIndex: cache.MetaNamespaceIndexFunc,
	}, i.tweakListOptions)
}
