---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-bind-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-bind.io
  resources:
  - apiresourceschemas
  - apiserviceexportrequests
  - apiserviceexports
  - apiservicenamespaces
  - boundschemas
  - clusterbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-bind.io
  resources:
  - apiserviceexportrequests/finalizers
  - apiserviceexports/finalizers
  - apiservicenamespaces/finalizers
  - clusterbindings/finalizers
  verbs:
  - update
- apiGroups:
  - kube-bind.io
  resources:
  - apiserviceexportrequests/status
  - apiserviceexports/status
  - apiservicenamespaces/status
  - clusterbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kube-bind.io
  resources:
  - apiserviceexporttemplates
  - collections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kube-bind.io
  resources:
  - boundschemas/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
