/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// APIServiceExportLister helps list APIServiceExports.
// All objects returned here must be treated as read-only.
type APIServiceExportLister interface {
	// List lists all APIServiceExports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.APIServiceExport, err error)
	// APIServiceExports returns an object that can list and get APIServiceExports.
	APIServiceExports(namespace string) APIServiceExportNamespaceLister
	APIServiceExportListerExpansion
}

// aPIServiceExportLister implements the APIServiceExportLister interface.
type aPIServiceExportLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.APIServiceExport]
}

// NewAPIServiceExportLister returns a new APIServiceExportLister.
func NewAPIServiceExportLister(indexer cache.Indexer) APIServiceExportLister {
	return &aPIServiceExportLister{listers.New[*kubebindv1alpha2.APIServiceExport](indexer, kubebindv1alpha2.Resource("apiserviceexport"))}
}

// APIServiceExports returns an object that can list and get APIServiceExports.
func (s *aPIServiceExportLister) APIServiceExports(namespace string) APIServiceExportNamespaceLister {
	return aPIServiceExportNamespaceLister{listers.NewNamespaced[*kubebindv1alpha2.APIServiceExport](s.ResourceIndexer, namespace)}
}

// APIServiceExportNamespaceLister helps list and get APIServiceExports.
// All objects returned here must be treated as read-only.
type APIServiceExportNamespaceLister interface {
	// List lists all APIServiceExports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.APIServiceExport, err error)
	// Get retrieves the APIServiceExport from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubebindv1alpha2.APIServiceExport, error)
	APIServiceExportNamespaceListerExpansion
}

// aPIServiceExportNamespaceLister implements the APIServiceExportNamespaceLister
// interface.
type aPIServiceExportNamespaceLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.APIServiceExport]
}
