/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
)

// BoundAPIResourceSchemaLister helps list BoundAPIResourceSchemas.
// All objects returned here must be treated as read-only.
type BoundAPIResourceSchemaLister interface {
	// List lists all BoundAPIResourceSchemas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.BoundAPIResourceSchema, err error)
	// BoundAPIResourceSchemas returns an object that can list and get BoundAPIResourceSchemas.
	BoundAPIResourceSchemas(namespace string) BoundAPIResourceSchemaNamespaceLister
	BoundAPIResourceSchemaListerExpansion
}

// boundAPIResourceSchemaLister implements the BoundAPIResourceSchemaLister interface.
type boundAPIResourceSchemaLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.BoundAPIResourceSchema]
}

// NewBoundAPIResourceSchemaLister returns a new BoundAPIResourceSchemaLister.
func NewBoundAPIResourceSchemaLister(indexer cache.Indexer) BoundAPIResourceSchemaLister {
	return &boundAPIResourceSchemaLister{listers.New[*kubebindv1alpha2.BoundAPIResourceSchema](indexer, kubebindv1alpha2.Resource("boundapiresourceschema"))}
}

// BoundAPIResourceSchemas returns an object that can list and get BoundAPIResourceSchemas.
func (s *boundAPIResourceSchemaLister) BoundAPIResourceSchemas(namespace string) BoundAPIResourceSchemaNamespaceLister {
	return boundAPIResourceSchemaNamespaceLister{listers.NewNamespaced[*kubebindv1alpha2.BoundAPIResourceSchema](s.ResourceIndexer, namespace)}
}

// BoundAPIResourceSchemaNamespaceLister helps list and get BoundAPIResourceSchemas.
// All objects returned here must be treated as read-only.
type BoundAPIResourceSchemaNamespaceLister interface {
	// List lists all BoundAPIResourceSchemas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.BoundAPIResourceSchema, err error)
	// Get retrieves the BoundAPIResourceSchema from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubebindv1alpha2.BoundAPIResourceSchema, error)
	BoundAPIResourceSchemaNamespaceListerExpansion
}

// boundAPIResourceSchemaNamespaceLister implements the BoundAPIResourceSchemaNamespaceLister
// interface.
type boundAPIResourceSchemaNamespaceLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.BoundAPIResourceSchema]
}
