/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CollectionLister helps list Collections.
// All objects returned here must be treated as read-only.
type CollectionLister interface {
	// List lists all Collections in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.Collection, err error)
	// Collections returns an object that can list and get Collections.
	Collections(namespace string) CollectionNamespaceLister
	CollectionListerExpansion
}

// collectionLister implements the CollectionLister interface.
type collectionLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.Collection]
}

// NewCollectionLister returns a new CollectionLister.
func NewCollectionLister(indexer cache.Indexer) CollectionLister {
	return &collectionLister{listers.New[*kubebindv1alpha2.Collection](indexer, kubebindv1alpha2.Resource("collection"))}
}

// Collections returns an object that can list and get Collections.
func (s *collectionLister) Collections(namespace string) CollectionNamespaceLister {
	return collectionNamespaceLister{listers.NewNamespaced[*kubebindv1alpha2.Collection](s.ResourceIndexer, namespace)}
}

// CollectionNamespaceLister helps list and get Collections.
// All objects returned here must be treated as read-only.
type CollectionNamespaceLister interface {
	// List lists all Collections in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha2.Collection, err error)
	// Get retrieves the Collection from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubebindv1alpha2.Collection, error)
	CollectionNamespaceListerExpansion
}

// collectionNamespaceLister implements the CollectionNamespaceLister
// interface.
type collectionNamespaceLister struct {
	listers.ResourceIndexer[*kubebindv1alpha2.Collection]
}
