apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tangodbs.tangodb.com
  labels:
    kube-bind.io/exported: "true"
spec:
  group: tangodb.com
  names:
    kind: TangoDB
    listKind: TangoDBList
    plural: tangodbs
    singular: tangodb
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tier:
                  type: string
                  enum:
                    - Dedicated
                    - Shared
                  default: Shared
            status:
              type: object
              properties:
                phase:
                  type: string
          required:
            - spec
      subresources:
        status: {}

