/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	kubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha1"
	v1alpha1 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha1"
	typedkcpkubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha1"
	typedkubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha1"
)

// aPIServiceExportRequestClusterClient implements APIServiceExportRequestClusterInterface
type aPIServiceExportRequestClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList]
	Fake *kcptesting.Fake
}

func newFakeAPIServiceExportRequestClusterClient(fake *KubeBindV1alpha1ClusterClient) typedkcpkubebindv1alpha1.APIServiceExportRequestClusterInterface {
	return &aPIServiceExportRequestClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList](
			fake.Fake,
			kubebindv1alpha1.SchemeGroupVersion.WithResource("apiserviceexportrequests"),
			kubebindv1alpha1.SchemeGroupVersion.WithKind("APIServiceExportRequest"),
			func() *kubebindv1alpha1.APIServiceExportRequest { return &kubebindv1alpha1.APIServiceExportRequest{} },
			func() *kubebindv1alpha1.APIServiceExportRequestList {
				return &kubebindv1alpha1.APIServiceExportRequestList{}
			},
			func(dst, src *kubebindv1alpha1.APIServiceExportRequestList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha1.APIServiceExportRequestList) []*kubebindv1alpha1.APIServiceExportRequest {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha1.APIServiceExportRequestList, items []*kubebindv1alpha1.APIServiceExportRequest) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *aPIServiceExportRequestClusterClient) Cluster(cluster logicalcluster.Path) typedkcpkubebindv1alpha1.APIServiceExportRequestsNamespacer {
	return &aPIServiceExportRequestNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type aPIServiceExportRequestNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *aPIServiceExportRequestNamespacer) Namespace(namespace string) typedkubebindv1alpha1.APIServiceExportRequestInterface {
	return newFakeAPIServiceExportRequestClient(n.Fake, namespace, n.ClusterPath)
}

// aPIServiceExportRequestScopedClient implements APIServiceExportRequestInterface
type aPIServiceExportRequestScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList, *v1alpha1.APIServiceExportRequestApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeAPIServiceExportRequestClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedkubebindv1alpha1.APIServiceExportRequestInterface {
	return &aPIServiceExportRequestScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList, *v1alpha1.APIServiceExportRequestApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			kubebindv1alpha1.SchemeGroupVersion.WithResource("apiserviceexportrequests"),
			kubebindv1alpha1.SchemeGroupVersion.WithKind("APIServiceExportRequest"),
			func() *kubebindv1alpha1.APIServiceExportRequest { return &kubebindv1alpha1.APIServiceExportRequest{} },
			func() *kubebindv1alpha1.APIServiceExportRequestList {
				return &kubebindv1alpha1.APIServiceExportRequestList{}
			},
			func(dst, src *kubebindv1alpha1.APIServiceExportRequestList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha1.APIServiceExportRequestList) []*kubebindv1alpha1.APIServiceExportRequest {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha1.APIServiceExportRequestList, items []*kubebindv1alpha1.APIServiceExportRequest) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
