/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	scheme "github.com/kube-bind/kube-bind/sdk/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// BindableResourcesRequestsGetter has a method to return a BindableResourcesRequestInterface.
// A group's client should implement this interface.
type BindableResourcesRequestsGetter interface {
	BindableResourcesRequests(namespace string) BindableResourcesRequestInterface
}

// BindableResourcesRequestInterface has methods to work with BindableResourcesRequest resources.
type BindableResourcesRequestInterface interface {
	Create(ctx context.Context, bindableResourcesRequest *kubebindv1alpha2.BindableResourcesRequest, opts v1.CreateOptions) (*kubebindv1alpha2.BindableResourcesRequest, error)
	Update(ctx context.Context, bindableResourcesRequest *kubebindv1alpha2.BindableResourcesRequest, opts v1.UpdateOptions) (*kubebindv1alpha2.BindableResourcesRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bindableResourcesRequest *kubebindv1alpha2.BindableResourcesRequest, opts v1.UpdateOptions) (*kubebindv1alpha2.BindableResourcesRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubebindv1alpha2.BindableResourcesRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubebindv1alpha2.BindableResourcesRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubebindv1alpha2.BindableResourcesRequest, err error)
	BindableResourcesRequestExpansion
}

// bindableResourcesRequests implements BindableResourcesRequestInterface
type bindableResourcesRequests struct {
	*gentype.ClientWithList[*kubebindv1alpha2.BindableResourcesRequest, *kubebindv1alpha2.BindableResourcesRequestList]
}

// newBindableResourcesRequests returns a BindableResourcesRequests
func newBindableResourcesRequests(c *KubeBindV1alpha2Client, namespace string) *bindableResourcesRequests {
	return &bindableResourcesRequests{
		gentype.NewClientWithList[*kubebindv1alpha2.BindableResourcesRequest, *kubebindv1alpha2.BindableResourcesRequestList](
			"bindableresourcesrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubebindv1alpha2.BindableResourcesRequest { return &kubebindv1alpha2.BindableResourcesRequest{} },
			func() *kubebindv1alpha2.BindableResourcesRequestList {
				return &kubebindv1alpha2.BindableResourcesRequestList{}
			},
		),
	}
}
