/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	scheme "github.com/kube-bind/kube-bind/sdk/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ClustersGetter has a method to return a ClusterInterface.
// A group's client should implement this interface.
type ClustersGetter interface {
	Clusters(namespace string) ClusterInterface
}

// ClusterInterface has methods to work with Cluster resources.
type ClusterInterface interface {
	Create(ctx context.Context, cluster *kubebindv1alpha2.Cluster, opts v1.CreateOptions) (*kubebindv1alpha2.Cluster, error)
	Update(ctx context.Context, cluster *kubebindv1alpha2.Cluster, opts v1.UpdateOptions) (*kubebindv1alpha2.Cluster, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, cluster *kubebindv1alpha2.Cluster, opts v1.UpdateOptions) (*kubebindv1alpha2.Cluster, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubebindv1alpha2.Cluster, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubebindv1alpha2.ClusterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubebindv1alpha2.Cluster, err error)
	ClusterExpansion
}

// clusters implements ClusterInterface
type clusters struct {
	*gentype.ClientWithList[*kubebindv1alpha2.Cluster, *kubebindv1alpha2.ClusterList]
}

// newClusters returns a Clusters
func newClusters(c *KubeBindV1alpha2Client, namespace string) *clusters {
	return &clusters{
		gentype.NewClientWithList[*kubebindv1alpha2.Cluster, *kubebindv1alpha2.ClusterList](
			"clusters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubebindv1alpha2.Cluster { return &kubebindv1alpha2.Cluster{} },
			func() *kubebindv1alpha2.ClusterList { return &kubebindv1alpha2.ClusterList{} },
		),
	}
}
