/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// APIServiceBindingListerExpansion allows custom methods to be added to
// APIServiceBindingLister.
type APIServiceBindingListerExpansion interface{}

// APIServiceExportListerExpansion allows custom methods to be added to
// APIServiceExportLister.
type APIServiceExportListerExpansion interface{}

// APIServiceExportNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportNamespaceLister.
type APIServiceExportNamespaceListerExpansion interface{}

// APIServiceExportResourceListerExpansion allows custom methods to be added to
// APIServiceExportResourceLister.
type APIServiceExportResourceListerExpansion interface{}

// APIServiceExportResourceNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportResourceNamespaceLister.
type APIServiceExportResourceNamespaceListerExpansion interface{}

// APIServiceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceLister.
type APIServiceNamespaceListerExpansion interface{}

// APIServiceNamespaceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceNamespaceLister.
type APIServiceNamespaceNamespaceListerExpansion interface{}

// APIServiceProviderListerExpansion allows custom methods to be added to
// APIServiceProviderLister.
type APIServiceProviderListerExpansion interface{}

// APIServiceProviderNamespaceListerExpansion allows custom methods to be added to
// APIServiceProviderNamespaceLister.
type APIServiceProviderNamespaceListerExpansion interface{}

// ClusterBindingListerExpansion allows custom methods to be added to
// ClusterBindingLister.
type ClusterBindingListerExpansion interface{}

// ClusterBindingNamespaceListerExpansion allows custom methods to be added to
// ClusterBindingNamespaceLister.
type ClusterBindingNamespaceListerExpansion interface{}

// ServiceBindingSessionListerExpansion allows custom methods to be added to
// ServiceBindingSessionLister.
type ServiceBindingSessionListerExpansion interface{}

// ServiceBindingSessionNamespaceListerExpansion allows custom methods to be added to
// ServiceBindingSessionNamespaceLister.
type ServiceBindingSessionNamespaceListerExpansion interface{}
