/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1alpha1

import (
	kcplisters "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/listers"
	"github.com/kcp-dev/logicalcluster/v3"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"

	kubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha1"
)

// APIServiceExportRequestClusterLister helps list APIServiceExportRequests across all workspaces,
// or scope down to a APIServiceExportRequestLister for one workspace.
// All objects returned here must be treated as read-only.
type APIServiceExportRequestClusterLister interface {
	// List lists all APIServiceExportRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha1.APIServiceExportRequest, err error)
	// Cluster returns a lister that can list and get APIServiceExportRequests in one workspace.
	Cluster(clusterName logicalcluster.Name) APIServiceExportRequestLister
	APIServiceExportRequestClusterListerExpansion
}

// aPIServiceExportRequestClusterLister implements the APIServiceExportRequestClusterLister interface.
type aPIServiceExportRequestClusterLister struct {
	kcplisters.ResourceClusterIndexer[*kubebindv1alpha1.APIServiceExportRequest]
}

var _ APIServiceExportRequestClusterLister = new(aPIServiceExportRequestClusterLister)

// NewAPIServiceExportRequestClusterLister returns a new APIServiceExportRequestClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewAPIServiceExportRequestClusterLister(indexer cache.Indexer) APIServiceExportRequestClusterLister {
	return &aPIServiceExportRequestClusterLister{
		kcplisters.NewCluster[*kubebindv1alpha1.APIServiceExportRequest](indexer, kubebindv1alpha1.Resource("apiserviceexportrequest")),
	}
}

// Cluster scopes the lister to one workspace, allowing users to list and get APIServiceExportRequests.
func (l *aPIServiceExportRequestClusterLister) Cluster(clusterName logicalcluster.Name) APIServiceExportRequestLister {
	return &aPIServiceExportRequestLister{
		l.ResourceClusterIndexer.WithCluster(clusterName),
	}
}

// aPIServiceExportRequestLister can list all APIServiceExportRequests inside a workspace
// or scope down to a APIServiceExportRequestNamespaceLister for one namespace.
type aPIServiceExportRequestLister struct {
	kcplisters.ResourceIndexer[*kubebindv1alpha1.APIServiceExportRequest]
}

var _ APIServiceExportRequestLister = new(aPIServiceExportRequestLister)

// APIServiceExportRequestLister can list APIServiceExportRequests across all namespaces, or scope down to a APIServiceExportRequestNamespaceLister for one namespace.
// All objects returned here must be treated as read-only.
type APIServiceExportRequestLister interface {
	// List lists all APIServiceExportRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha1.APIServiceExportRequest, err error)
	// APIServiceExportRequests returns a lister that can list and get APIServiceExportRequests in one workspace and namespace.
	APIServiceExportRequests(namespace string) APIServiceExportRequestNamespaceLister
	APIServiceExportRequestListerExpansion
}

// APIServiceExportRequests returns an object that can list and get APIServiceExportRequests in one namespace.
func (l *aPIServiceExportRequestLister) APIServiceExportRequests(namespace string) APIServiceExportRequestNamespaceLister {
	return &aPIServiceExportRequestNamespaceLister{
		l.ResourceIndexer.WithNamespace(namespace),
	}
}

// aPIServiceExportRequestNamespaceLister implements the APIServiceExportRequestNamespaceLister
// interface.
type aPIServiceExportRequestNamespaceLister struct {
	kcplisters.ResourceIndexer[*kubebindv1alpha1.APIServiceExportRequest]
}

var _ APIServiceExportRequestNamespaceLister = new(aPIServiceExportRequestNamespaceLister)

// APIServiceExportRequestNamespaceLister can list all APIServiceExportRequests, or get one in particular.
// All objects returned here must be treated as read-only.
type APIServiceExportRequestNamespaceLister interface {
	// List lists all APIServiceExportRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubebindv1alpha1.APIServiceExportRequest, err error)
	// Get retrieves the APIServiceExportRequest from the indexer for a given workspace, namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubebindv1alpha1.APIServiceExportRequest, error)
	APIServiceExportRequestNamespaceListerExpansion
}

// NewAPIServiceExportRequestLister returns a new APIServiceExportRequestLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
// - has the kcpcache.ClusterAndNamespaceIndex as an index
func NewAPIServiceExportRequestLister(indexer cache.Indexer) APIServiceExportRequestLister {
	return &aPIServiceExportRequestLister{
		kcplisters.New[*kubebindv1alpha1.APIServiceExportRequest](indexer, kubebindv1alpha1.Resource("apiserviceexportrequest")),
	}
}

// aPIServiceExportRequestScopedLister can list all APIServiceExportRequests inside a workspace
// or scope down to a APIServiceExportRequestNamespaceLister for one namespace.
type aPIServiceExportRequestScopedLister struct {
	kcplisters.ResourceIndexer[*kubebindv1alpha1.APIServiceExportRequest]
}

// APIServiceExportRequests returns an object that can list and get APIServiceExportRequests in one namespace.
func (l *aPIServiceExportRequestScopedLister) APIServiceExportRequests(namespace string) APIServiceExportRequestLister {
	return &aPIServiceExportRequestLister{
		l.ResourceIndexer.WithNamespace(namespace),
	}
}
