/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	catalogv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/catalog/v1alpha1"
	scheme "github.com/kube-bind/kube-bind/sdk/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CollectionsGetter has a method to return a CollectionInterface.
// A group's client should implement this interface.
type CollectionsGetter interface {
	Collections(namespace string) CollectionInterface
}

// CollectionInterface has methods to work with Collection resources.
type CollectionInterface interface {
	Create(ctx context.Context, collection *catalogv1alpha1.Collection, opts v1.CreateOptions) (*catalogv1alpha1.Collection, error)
	Update(ctx context.Context, collection *catalogv1alpha1.Collection, opts v1.UpdateOptions) (*catalogv1alpha1.Collection, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, collection *catalogv1alpha1.Collection, opts v1.UpdateOptions) (*catalogv1alpha1.Collection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*catalogv1alpha1.Collection, error)
	List(ctx context.Context, opts v1.ListOptions) (*catalogv1alpha1.CollectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *catalogv1alpha1.Collection, err error)
	CollectionExpansion
}

// collections implements CollectionInterface
type collections struct {
	*gentype.ClientWithList[*catalogv1alpha1.Collection, *catalogv1alpha1.CollectionList]
}

// newCollections returns a Collections
func newCollections(c *CatalogV1alpha1Client, namespace string) *collections {
	return &collections{
		gentype.NewClientWithList[*catalogv1alpha1.Collection, *catalogv1alpha1.CollectionList](
			"collections",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *catalogv1alpha1.Collection { return &catalogv1alpha1.Collection{} },
			func() *catalogv1alpha1.CollectionList { return &catalogv1alpha1.CollectionList{} },
		),
	}
}
