apiVersion: kube-bind.io/v1alpha2
kind: APIServiceExportTemplate
metadata:
  name: sheriffs
spec:
  scope: Cluster
  resources:
  - group: wildwest.dev
    versions: 
    - v1alpha1
    resource: sheriffs
  permissionClaims:
  - group: ""
    resource: secrets
    selector:
      namedResources:
      - name: sheriff-badge-credentials
      - name: sheriff-jurisdiction-config
      labelSelector:
        matchLabels:
          app: sheriff
          security: high
  - group: ""
    resource: configmaps
    selector:
      namedResources:
      - name: sheriff-jurisdiction-map
      - name: sheriff-enforcement-rules
      labelSelector:
        matchLabels:
          app: sheriff
          component: enforcement
  namespaces:
  - name: sheriff-operations
  - name: sheriff-intelligence