/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.32. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	kubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha1"
	applyconfigurationkubebindv1alpha1 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha1"
	scheme "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/scheme"
)

// APIServiceExportRequestsGetter has a method to return a APIServiceExportRequestInterface.
// A group's client should implement this interface.
type APIServiceExportRequestsGetter interface {
	APIServiceExportRequests(namespace string) APIServiceExportRequestInterface
}

// APIServiceExportRequestInterface has methods to work with APIServiceExportRequest resources.
type APIServiceExportRequestInterface interface {
	Create(ctx context.Context, aPIServiceExportRequest *kubebindv1alpha1.APIServiceExportRequest, opts v1.CreateOptions) (*kubebindv1alpha1.APIServiceExportRequest, error)
	Update(ctx context.Context, aPIServiceExportRequest *kubebindv1alpha1.APIServiceExportRequest, opts v1.UpdateOptions) (*kubebindv1alpha1.APIServiceExportRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, aPIServiceExportRequest *kubebindv1alpha1.APIServiceExportRequest, opts v1.UpdateOptions) (*kubebindv1alpha1.APIServiceExportRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubebindv1alpha1.APIServiceExportRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubebindv1alpha1.APIServiceExportRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubebindv1alpha1.APIServiceExportRequest, err error)
	Apply(ctx context.Context, aPIServiceExportRequest *applyconfigurationkubebindv1alpha1.APIServiceExportRequestApplyConfiguration, opts v1.ApplyOptions) (result *kubebindv1alpha1.APIServiceExportRequest, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, aPIServiceExportRequest *applyconfigurationkubebindv1alpha1.APIServiceExportRequestApplyConfiguration, opts v1.ApplyOptions) (result *kubebindv1alpha1.APIServiceExportRequest, err error)
	APIServiceExportRequestExpansion
}

// aPIServiceExportRequests implements APIServiceExportRequestInterface
type aPIServiceExportRequests struct {
	*gentype.ClientWithListAndApply[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList, *applyconfigurationkubebindv1alpha1.APIServiceExportRequestApplyConfiguration]
}

// newAPIServiceExportRequests returns a APIServiceExportRequests
func newAPIServiceExportRequests(c *KubeBindV1alpha1Client, namespace string) *aPIServiceExportRequests {
	return &aPIServiceExportRequests{
		gentype.NewClientWithListAndApply[*kubebindv1alpha1.APIServiceExportRequest, *kubebindv1alpha1.APIServiceExportRequestList, *applyconfigurationkubebindv1alpha1.APIServiceExportRequestApplyConfiguration](
			"apiserviceexportrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubebindv1alpha1.APIServiceExportRequest { return &kubebindv1alpha1.APIServiceExportRequest{} },
			func() *kubebindv1alpha1.APIServiceExportRequestList {
				return &kubebindv1alpha1.APIServiceExportRequestList{}
			},
		),
	}
}
