/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha1 "github.com/kube-bind/kube-bind/pkg/apis/kubebind/v1alpha1"
)

// FakeAPIServiceProviders implements APIServiceProviderInterface
type FakeAPIServiceProviders struct {
	Fake *FakeKubeBindV1alpha1
	ns   string
}

var apiserviceprovidersResource = schema.GroupVersionResource{Group: "kube-bind.io", Version: "v1alpha1", Resource: "apiserviceproviders"}

var apiserviceprovidersKind = schema.GroupVersionKind{Group: "kube-bind.io", Version: "v1alpha1", Kind: "APIServiceProvider"}

// Get takes name of the aPIServiceProvider, and returns the corresponding aPIServiceProvider object, and an error if there is any.
func (c *FakeAPIServiceProviders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.APIServiceProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(apiserviceprovidersResource, c.ns, name), &v1alpha1.APIServiceProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIServiceProvider), err
}

// List takes label and field selectors, and returns the list of APIServiceProviders that match those selectors.
func (c *FakeAPIServiceProviders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.APIServiceProviderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(apiserviceprovidersResource, apiserviceprovidersKind, c.ns, opts), &v1alpha1.APIServiceProviderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.APIServiceProviderList{ListMeta: obj.(*v1alpha1.APIServiceProviderList).ListMeta}
	for _, item := range obj.(*v1alpha1.APIServiceProviderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aPIServiceProviders.
func (c *FakeAPIServiceProviders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(apiserviceprovidersResource, c.ns, opts))

}

// Create takes the representation of a aPIServiceProvider and creates it.  Returns the server's representation of the aPIServiceProvider, and an error, if there is any.
func (c *FakeAPIServiceProviders) Create(ctx context.Context, aPIServiceProvider *v1alpha1.APIServiceProvider, opts v1.CreateOptions) (result *v1alpha1.APIServiceProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(apiserviceprovidersResource, c.ns, aPIServiceProvider), &v1alpha1.APIServiceProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIServiceProvider), err
}

// Update takes the representation of a aPIServiceProvider and updates it. Returns the server's representation of the aPIServiceProvider, and an error, if there is any.
func (c *FakeAPIServiceProviders) Update(ctx context.Context, aPIServiceProvider *v1alpha1.APIServiceProvider, opts v1.UpdateOptions) (result *v1alpha1.APIServiceProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(apiserviceprovidersResource, c.ns, aPIServiceProvider), &v1alpha1.APIServiceProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIServiceProvider), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAPIServiceProviders) UpdateStatus(ctx context.Context, aPIServiceProvider *v1alpha1.APIServiceProvider, opts v1.UpdateOptions) (*v1alpha1.APIServiceProvider, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(apiserviceprovidersResource, "status", c.ns, aPIServiceProvider), &v1alpha1.APIServiceProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIServiceProvider), err
}

// Delete takes name of the aPIServiceProvider and deletes it. Returns an error if one occurs.
func (c *FakeAPIServiceProviders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(apiserviceprovidersResource, c.ns, name, opts), &v1alpha1.APIServiceProvider{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAPIServiceProviders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(apiserviceprovidersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.APIServiceProviderList{})
	return err
}

// Patch applies the patch and returns the patched aPIServiceProvider.
func (c *FakeAPIServiceProviders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.APIServiceProvider, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(apiserviceprovidersResource, c.ns, name, pt, data, subresources...), &v1alpha1.APIServiceProvider{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.APIServiceProvider), err
}
