/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-informer-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"
	time "time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	logicalcluster "github.com/kcp-dev/logicalcluster/v3"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"

	apiskubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	versioned "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned"
	internalinterfaces "github.com/kube-bind/kube-bind/sdk/kcp/informers/externalversions/internalinterfaces"
	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/listers/kubebind/v1alpha2"
)

// APIResourceSchemaClusterInformer provides access to a shared informer and lister for
// APIResourceSchemas.
type APIResourceSchemaClusterInformer interface {
	Cluster(logicalcluster.Name) APIResourceSchemaInformer
	ClusterWithContext(context.Context, logicalcluster.Name) APIResourceSchemaInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() kubebindv1alpha2.APIResourceSchemaClusterLister
}

type aPIResourceSchemaClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAPIResourceSchemaClusterInformer constructs a new informer for APIResourceSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAPIResourceSchemaClusterInformer(client versioned.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredAPIResourceSchemaClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAPIResourceSchemaClusterInformer constructs a new informer for APIResourceSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIResourceSchemaClusterInformer(client versioned.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha2().APIResourceSchemas().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha2().APIResourceSchemas().Watch(context.Background(), options)
			},
		},
		&apiskubebindv1alpha2.APIResourceSchema{},
		resyncPeriod,
		indexers,
	)
}

func (i *aPIResourceSchemaClusterInformer) defaultInformer(client versioned.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredAPIResourceSchemaClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc,
	}, i.tweakListOptions)
}

func (i *aPIResourceSchemaClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return i.factory.InformerFor(&apiskubebindv1alpha2.APIResourceSchema{}, i.defaultInformer)
}

func (i *aPIResourceSchemaClusterInformer) Lister() kubebindv1alpha2.APIResourceSchemaClusterLister {
	return kubebindv1alpha2.NewAPIResourceSchemaClusterLister(i.Informer().GetIndexer())
}

func (i *aPIResourceSchemaClusterInformer) Cluster(clusterName logicalcluster.Name) APIResourceSchemaInformer {
	return &aPIResourceSchemaInformer{
		informer: i.Informer().Cluster(clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

func (i *aPIResourceSchemaClusterInformer) ClusterWithContext(ctx context.Context, clusterName logicalcluster.Name) APIResourceSchemaInformer {
	return &aPIResourceSchemaInformer{
		informer: i.Informer().ClusterWithContext(ctx, clusterName),
		lister:   i.Lister().Cluster(clusterName),
	}
}

type aPIResourceSchemaInformer struct {
	informer cache.SharedIndexInformer
	lister   kubebindv1alpha2.APIResourceSchemaLister
}

func (i *aPIResourceSchemaInformer) Informer() cache.SharedIndexInformer {
	return i.informer
}

func (i *aPIResourceSchemaInformer) Lister() kubebindv1alpha2.APIResourceSchemaLister {
	return i.lister
}

// APIResourceSchemaInformer provides access to a shared informer and lister for
// APIResourceSchemas.
type APIResourceSchemaInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() kubebindv1alpha2.APIResourceSchemaLister
}

type aPIResourceSchemaScopedInformer struct {
	factory          internalinterfaces.SharedScopedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAPIResourceSchemaInformer constructs a new informer for APIResourceSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAPIResourceSchemaInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAPIResourceSchemaInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAPIResourceSchemaInformer constructs a new informer for APIResourceSchema type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAPIResourceSchemaInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha2().APIResourceSchemas().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubeBindV1alpha2().APIResourceSchemas().Watch(context.Background(), options)
			},
		},
		&apiskubebindv1alpha2.APIResourceSchema{},
		resyncPeriod,
		indexers,
	)
}

func (i *aPIResourceSchemaScopedInformer) Informer() cache.SharedIndexInformer {
	return i.factory.InformerFor(&apiskubebindv1alpha2.APIResourceSchema{}, i.defaultInformer)
}

func (i *aPIResourceSchemaScopedInformer) Lister() kubebindv1alpha2.APIResourceSchemaLister {
	return kubebindv1alpha2.NewAPIResourceSchemaLister(i.Informer().GetIndexer())
}

func (i *aPIResourceSchemaScopedInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAPIResourceSchemaInformer(client, resyncPeriod, cache.Indexers{}, i.tweakListOptions)
}
