/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-lister-gen. DO NOT EDIT.

package v1alpha2

// APIResourceSchemaClusterListerExpansion allows custom methods to be added to
// APIResourceSchemaClusterLister.
type APIResourceSchemaClusterListerExpansion interface{}

// APIResourceSchemaListerExpansion allows custom methods to be added to
// APIResourceSchemaLister.
type APIResourceSchemaListerExpansion interface{}

// APIServiceBindingClusterListerExpansion allows custom methods to be added to
// APIServiceBindingClusterLister.
type APIServiceBindingClusterListerExpansion interface{}

// APIServiceBindingListerExpansion allows custom methods to be added to
// APIServiceBindingLister.
type APIServiceBindingListerExpansion interface{}

// APIServiceExportClusterListerExpansion allows custom methods to be added to
// APIServiceExportClusterLister.
type APIServiceExportClusterListerExpansion interface{}

// APIServiceExportListerExpansion allows custom methods to be added to
// APIServiceExportLister.
type APIServiceExportListerExpansion interface{}

// APIServiceExportNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportNamespaceLister.
type APIServiceExportNamespaceListerExpansion interface{}

// APIServiceExportRequestClusterListerExpansion allows custom methods to be added to
// APIServiceExportRequestClusterLister.
type APIServiceExportRequestClusterListerExpansion interface{}

// APIServiceExportRequestListerExpansion allows custom methods to be added to
// APIServiceExportRequestLister.
type APIServiceExportRequestListerExpansion interface{}

// APIServiceExportRequestNamespaceListerExpansion allows custom methods to be added to
// APIServiceExportRequestNamespaceLister.
type APIServiceExportRequestNamespaceListerExpansion interface{}

// APIServiceNamespaceClusterListerExpansion allows custom methods to be added to
// APIServiceNamespaceClusterLister.
type APIServiceNamespaceClusterListerExpansion interface{}

// APIServiceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceLister.
type APIServiceNamespaceListerExpansion interface{}

// APIServiceNamespaceNamespaceListerExpansion allows custom methods to be added to
// APIServiceNamespaceNamespaceLister.
type APIServiceNamespaceNamespaceListerExpansion interface{}

// BoundAPIResourceSchemaClusterListerExpansion allows custom methods to be added to
// BoundAPIResourceSchemaClusterLister.
type BoundAPIResourceSchemaClusterListerExpansion interface{}

// BoundAPIResourceSchemaListerExpansion allows custom methods to be added to
// BoundAPIResourceSchemaLister.
type BoundAPIResourceSchemaListerExpansion interface{}

// BoundAPIResourceSchemaNamespaceListerExpansion allows custom methods to be added to
// BoundAPIResourceSchemaNamespaceLister.
type BoundAPIResourceSchemaNamespaceListerExpansion interface{}

// ClusterBindingClusterListerExpansion allows custom methods to be added to
// ClusterBindingClusterLister.
type ClusterBindingClusterListerExpansion interface{}

// ClusterBindingListerExpansion allows custom methods to be added to
// ClusterBindingLister.
type ClusterBindingListerExpansion interface{}

// ClusterBindingNamespaceListerExpansion allows custom methods to be added to
// ClusterBindingNamespaceLister.
type ClusterBindingNamespaceListerExpansion interface{}
