name: Release

on:
  pull_request:
    paths:
    - .github/workflows/goreleaser.yaml
    - .goreleaser.yaml
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 0
    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version: v1.26.2
    - name: Delete non-semver tags
      run: 'git tag -d $(git tag -l | grep -v "^v")'
    - name: Set LDFLAGS
      run: echo LDFLAGS="$(make ldflags)" >> $GITHUB_ENV
    - name: Run GoReleaser on tag
      if: github.event_name != 'pull_request'
      uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}
    - name: Run GoReleaser on pull request
      if: github.event_name == 'pull_request'
      uses: goreleaser/goreleaser-action@5daf1e915a5f0af01ddbcd89a43b8061ff4f1a89 # v7.2.2
      with:
        distribution: goreleaser
        version: latest
        args: release --timeout 60m --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        KREW_GITHUB_TOKEN: ${{ secrets.KREW_GITHUB_TOKEN }}
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ always() }}
      with:
        name: binaries
        path: dist/*.tar.gz
