/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	v1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha2"
	typedkcpkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
	typedkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
)

// aPIResourceSchemaClusterClient implements APIResourceSchemaClusterInterface
type aPIResourceSchemaClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*kubebindv1alpha2.APIResourceSchema, *kubebindv1alpha2.APIResourceSchemaList]
	Fake *kcptesting.Fake
}

func newFakeAPIResourceSchemaClusterClient(fake *KubeBindV1alpha2ClusterClient) typedkcpkubebindv1alpha2.APIResourceSchemaClusterInterface {
	return &aPIResourceSchemaClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*kubebindv1alpha2.APIResourceSchema, *kubebindv1alpha2.APIResourceSchemaList](
			fake.Fake,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiresourceschemas"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIResourceSchema"),
			func() *kubebindv1alpha2.APIResourceSchema { return &kubebindv1alpha2.APIResourceSchema{} },
			func() *kubebindv1alpha2.APIResourceSchemaList { return &kubebindv1alpha2.APIResourceSchemaList{} },
			func(dst, src *kubebindv1alpha2.APIResourceSchemaList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIResourceSchemaList) []*kubebindv1alpha2.APIResourceSchema {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIResourceSchemaList, items []*kubebindv1alpha2.APIResourceSchema) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *aPIResourceSchemaClusterClient) Cluster(cluster logicalcluster.Path) typedkubebindv1alpha2.APIResourceSchemaInterface {
	return newFakeAPIResourceSchemaClient(c.Fake, cluster)
}

// aPIResourceSchemaScopedClient implements APIResourceSchemaInterface
type aPIResourceSchemaScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*kubebindv1alpha2.APIResourceSchema, *kubebindv1alpha2.APIResourceSchemaList, *v1alpha2.APIResourceSchemaApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeAPIResourceSchemaClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedkubebindv1alpha2.APIResourceSchemaInterface {
	return &aPIResourceSchemaScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*kubebindv1alpha2.APIResourceSchema, *kubebindv1alpha2.APIResourceSchemaList, *v1alpha2.APIResourceSchemaApplyConfiguration](
			fake,
			clusterPath,
			"",
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiresourceschemas"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIResourceSchema"),
			func() *kubebindv1alpha2.APIResourceSchema { return &kubebindv1alpha2.APIResourceSchema{} },
			func() *kubebindv1alpha2.APIResourceSchemaList { return &kubebindv1alpha2.APIResourceSchemaList{} },
			func(dst, src *kubebindv1alpha2.APIResourceSchemaList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIResourceSchemaList) []*kubebindv1alpha2.APIResourceSchema {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIResourceSchemaList, items []*kubebindv1alpha2.APIResourceSchema) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
