/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	v1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha2"
	typedkcpkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
	typedkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
)

// aPIServiceNamespaceClusterClient implements APIServiceNamespaceClusterInterface
type aPIServiceNamespaceClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*kubebindv1alpha2.APIServiceNamespace, *kubebindv1alpha2.APIServiceNamespaceList]
	Fake *kcptesting.Fake
}

func newFakeAPIServiceNamespaceClusterClient(fake *KubeBindV1alpha2ClusterClient) typedkcpkubebindv1alpha2.APIServiceNamespaceClusterInterface {
	return &aPIServiceNamespaceClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*kubebindv1alpha2.APIServiceNamespace, *kubebindv1alpha2.APIServiceNamespaceList](
			fake.Fake,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiservicenamespaces"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIServiceNamespace"),
			func() *kubebindv1alpha2.APIServiceNamespace { return &kubebindv1alpha2.APIServiceNamespace{} },
			func() *kubebindv1alpha2.APIServiceNamespaceList { return &kubebindv1alpha2.APIServiceNamespaceList{} },
			func(dst, src *kubebindv1alpha2.APIServiceNamespaceList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIServiceNamespaceList) []*kubebindv1alpha2.APIServiceNamespace {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIServiceNamespaceList, items []*kubebindv1alpha2.APIServiceNamespace) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *aPIServiceNamespaceClusterClient) Cluster(cluster logicalcluster.Path) typedkcpkubebindv1alpha2.APIServiceNamespacesNamespacer {
	return &aPIServiceNamespaceNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type aPIServiceNamespaceNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *aPIServiceNamespaceNamespacer) Namespace(namespace string) typedkubebindv1alpha2.APIServiceNamespaceInterface {
	return newFakeAPIServiceNamespaceClient(n.Fake, namespace, n.ClusterPath)
}

// aPIServiceNamespaceScopedClient implements APIServiceNamespaceInterface
type aPIServiceNamespaceScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*kubebindv1alpha2.APIServiceNamespace, *kubebindv1alpha2.APIServiceNamespaceList, *v1alpha2.APIServiceNamespaceApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeAPIServiceNamespaceClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedkubebindv1alpha2.APIServiceNamespaceInterface {
	return &aPIServiceNamespaceScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*kubebindv1alpha2.APIServiceNamespace, *kubebindv1alpha2.APIServiceNamespaceList, *v1alpha2.APIServiceNamespaceApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiservicenamespaces"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIServiceNamespace"),
			func() *kubebindv1alpha2.APIServiceNamespace { return &kubebindv1alpha2.APIServiceNamespace{} },
			func() *kubebindv1alpha2.APIServiceNamespaceList { return &kubebindv1alpha2.APIServiceNamespaceList{} },
			func(dst, src *kubebindv1alpha2.APIServiceNamespaceList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIServiceNamespaceList) []*kubebindv1alpha2.APIServiceNamespace {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIServiceNamespaceList, items []*kubebindv1alpha2.APIServiceNamespace) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
