/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	v1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha2"
	typedkcpkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
	typedkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
)

// aPIServiceBindingClusterClient implements APIServiceBindingClusterInterface
type aPIServiceBindingClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*kubebindv1alpha2.APIServiceBinding, *kubebindv1alpha2.APIServiceBindingList]
	Fake *kcptesting.Fake
}

func newFakeAPIServiceBindingClusterClient(fake *KubeBindV1alpha2ClusterClient) typedkcpkubebindv1alpha2.APIServiceBindingClusterInterface {
	return &aPIServiceBindingClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*kubebindv1alpha2.APIServiceBinding, *kubebindv1alpha2.APIServiceBindingList](
			fake.Fake,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiservicebindings"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIServiceBinding"),
			func() *kubebindv1alpha2.APIServiceBinding { return &kubebindv1alpha2.APIServiceBinding{} },
			func() *kubebindv1alpha2.APIServiceBindingList { return &kubebindv1alpha2.APIServiceBindingList{} },
			func(dst, src *kubebindv1alpha2.APIServiceBindingList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIServiceBindingList) []*kubebindv1alpha2.APIServiceBinding {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIServiceBindingList, items []*kubebindv1alpha2.APIServiceBinding) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *aPIServiceBindingClusterClient) Cluster(cluster logicalcluster.Path) typedkubebindv1alpha2.APIServiceBindingInterface {
	return newFakeAPIServiceBindingClient(c.Fake, cluster)
}

// aPIServiceBindingScopedClient implements APIServiceBindingInterface
type aPIServiceBindingScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*kubebindv1alpha2.APIServiceBinding, *kubebindv1alpha2.APIServiceBindingList, *v1alpha2.APIServiceBindingApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeAPIServiceBindingClient(fake *kcptesting.Fake, clusterPath logicalcluster.Path) typedkubebindv1alpha2.APIServiceBindingInterface {
	return &aPIServiceBindingScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*kubebindv1alpha2.APIServiceBinding, *kubebindv1alpha2.APIServiceBindingList, *v1alpha2.APIServiceBindingApplyConfiguration](
			fake,
			clusterPath,
			"",
			kubebindv1alpha2.SchemeGroupVersion.WithResource("apiservicebindings"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("APIServiceBinding"),
			func() *kubebindv1alpha2.APIServiceBinding { return &kubebindv1alpha2.APIServiceBinding{} },
			func() *kubebindv1alpha2.APIServiceBindingList { return &kubebindv1alpha2.APIServiceBindingList{} },
			func(dst, src *kubebindv1alpha2.APIServiceBindingList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.APIServiceBindingList) []*kubebindv1alpha2.APIServiceBinding {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.APIServiceBindingList, items []*kubebindv1alpha2.APIServiceBinding) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
