/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by cluster-client-gen. DO NOT EDIT.

package fake

import (
	kcpgentype "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/gentype"
	kcptesting "github.com/kcp-dev/client-go/third_party/k8s.io/client-go/testing"
	"github.com/kcp-dev/logicalcluster/v3"

	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	v1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha2"
	typedkcpkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
	typedkubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/clientset/versioned/typed/kubebind/v1alpha2"
)

// boundAPIResourceSchemaClusterClient implements BoundAPIResourceSchemaClusterInterface
type boundAPIResourceSchemaClusterClient struct {
	*kcpgentype.FakeClusterClientWithList[*kubebindv1alpha2.BoundAPIResourceSchema, *kubebindv1alpha2.BoundAPIResourceSchemaList]
	Fake *kcptesting.Fake
}

func newFakeBoundAPIResourceSchemaClusterClient(fake *KubeBindV1alpha2ClusterClient) typedkcpkubebindv1alpha2.BoundAPIResourceSchemaClusterInterface {
	return &boundAPIResourceSchemaClusterClient{
		kcpgentype.NewFakeClusterClientWithList[*kubebindv1alpha2.BoundAPIResourceSchema, *kubebindv1alpha2.BoundAPIResourceSchemaList](
			fake.Fake,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("boundapiresourceschemas"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("BoundAPIResourceSchema"),
			func() *kubebindv1alpha2.BoundAPIResourceSchema { return &kubebindv1alpha2.BoundAPIResourceSchema{} },
			func() *kubebindv1alpha2.BoundAPIResourceSchemaList {
				return &kubebindv1alpha2.BoundAPIResourceSchemaList{}
			},
			func(dst, src *kubebindv1alpha2.BoundAPIResourceSchemaList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.BoundAPIResourceSchemaList) []*kubebindv1alpha2.BoundAPIResourceSchema {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.BoundAPIResourceSchemaList, items []*kubebindv1alpha2.BoundAPIResourceSchema) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake.Fake,
	}
}

func (c *boundAPIResourceSchemaClusterClient) Cluster(cluster logicalcluster.Path) typedkcpkubebindv1alpha2.BoundAPIResourceSchemasNamespacer {
	return &boundAPIResourceSchemaNamespacer{Fake: c.Fake, ClusterPath: cluster}
}

type boundAPIResourceSchemaNamespacer struct {
	*kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func (n *boundAPIResourceSchemaNamespacer) Namespace(namespace string) typedkubebindv1alpha2.BoundAPIResourceSchemaInterface {
	return newFakeBoundAPIResourceSchemaClient(n.Fake, namespace, n.ClusterPath)
}

// boundAPIResourceSchemaScopedClient implements BoundAPIResourceSchemaInterface
type boundAPIResourceSchemaScopedClient struct {
	*kcpgentype.FakeClientWithListAndApply[*kubebindv1alpha2.BoundAPIResourceSchema, *kubebindv1alpha2.BoundAPIResourceSchemaList, *v1alpha2.BoundAPIResourceSchemaApplyConfiguration]
	Fake        *kcptesting.Fake
	ClusterPath logicalcluster.Path
}

func newFakeBoundAPIResourceSchemaClient(fake *kcptesting.Fake, namespace string, clusterPath logicalcluster.Path) typedkubebindv1alpha2.BoundAPIResourceSchemaInterface {
	return &boundAPIResourceSchemaScopedClient{
		kcpgentype.NewFakeClientWithListAndApply[*kubebindv1alpha2.BoundAPIResourceSchema, *kubebindv1alpha2.BoundAPIResourceSchemaList, *v1alpha2.BoundAPIResourceSchemaApplyConfiguration](
			fake,
			clusterPath,
			namespace,
			kubebindv1alpha2.SchemeGroupVersion.WithResource("boundapiresourceschemas"),
			kubebindv1alpha2.SchemeGroupVersion.WithKind("BoundAPIResourceSchema"),
			func() *kubebindv1alpha2.BoundAPIResourceSchema { return &kubebindv1alpha2.BoundAPIResourceSchema{} },
			func() *kubebindv1alpha2.BoundAPIResourceSchemaList {
				return &kubebindv1alpha2.BoundAPIResourceSchemaList{}
			},
			func(dst, src *kubebindv1alpha2.BoundAPIResourceSchemaList) { dst.ListMeta = src.ListMeta },
			func(list *kubebindv1alpha2.BoundAPIResourceSchemaList) []*kubebindv1alpha2.BoundAPIResourceSchema {
				return kcpgentype.ToPointerSlice(list.Items)
			},
			func(list *kubebindv1alpha2.BoundAPIResourceSchemaList, items []*kubebindv1alpha2.BoundAPIResourceSchema) {
				list.Items = kcpgentype.FromPointerSlice(items)
			},
		),
		fake,
		clusterPath,
	}
}
