/*
Copyright The Kube Bind Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen-v0.31. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"

	v1alpha2 "github.com/kube-bind/kube-bind/sdk/apis/kubebind/v1alpha2"
	kubebindv1alpha2 "github.com/kube-bind/kube-bind/sdk/kcp/applyconfiguration/kubebind/v1alpha2"
)

// FakeBoundAPIResourceSchemas implements BoundAPIResourceSchemaInterface
type FakeBoundAPIResourceSchemas struct {
	Fake *FakeKubeBindV1alpha2
	ns   string
}

var boundapiresourceschemasResource = v1alpha2.SchemeGroupVersion.WithResource("boundapiresourceschemas")

var boundapiresourceschemasKind = v1alpha2.SchemeGroupVersion.WithKind("BoundAPIResourceSchema")

// Get takes name of the boundAPIResourceSchema, and returns the corresponding boundAPIResourceSchema object, and an error if there is any.
func (c *FakeBoundAPIResourceSchemas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(boundapiresourceschemasResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// List takes label and field selectors, and returns the list of BoundAPIResourceSchemas that match those selectors.
func (c *FakeBoundAPIResourceSchemas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.BoundAPIResourceSchemaList, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchemaList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(boundapiresourceschemasResource, boundapiresourceschemasKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.BoundAPIResourceSchemaList{ListMeta: obj.(*v1alpha2.BoundAPIResourceSchemaList).ListMeta}
	for _, item := range obj.(*v1alpha2.BoundAPIResourceSchemaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested boundAPIResourceSchemas.
func (c *FakeBoundAPIResourceSchemas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(boundapiresourceschemasResource, c.ns, opts))

}

// Create takes the representation of a boundAPIResourceSchema and creates it.  Returns the server's representation of the boundAPIResourceSchema, and an error, if there is any.
func (c *FakeBoundAPIResourceSchemas) Create(ctx context.Context, boundAPIResourceSchema *v1alpha2.BoundAPIResourceSchema, opts v1.CreateOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(boundapiresourceschemasResource, c.ns, boundAPIResourceSchema, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// Update takes the representation of a boundAPIResourceSchema and updates it. Returns the server's representation of the boundAPIResourceSchema, and an error, if there is any.
func (c *FakeBoundAPIResourceSchemas) Update(ctx context.Context, boundAPIResourceSchema *v1alpha2.BoundAPIResourceSchema, opts v1.UpdateOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(boundapiresourceschemasResource, c.ns, boundAPIResourceSchema, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBoundAPIResourceSchemas) UpdateStatus(ctx context.Context, boundAPIResourceSchema *v1alpha2.BoundAPIResourceSchema, opts v1.UpdateOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(boundapiresourceschemasResource, "status", c.ns, boundAPIResourceSchema, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// Delete takes name of the boundAPIResourceSchema and deletes it. Returns an error if one occurs.
func (c *FakeBoundAPIResourceSchemas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(boundapiresourceschemasResource, c.ns, name, opts), &v1alpha2.BoundAPIResourceSchema{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBoundAPIResourceSchemas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(boundapiresourceschemasResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.BoundAPIResourceSchemaList{})
	return err
}

// Patch applies the patch and returns the patched boundAPIResourceSchema.
func (c *FakeBoundAPIResourceSchemas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(boundapiresourceschemasResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied boundAPIResourceSchema.
func (c *FakeBoundAPIResourceSchemas) Apply(ctx context.Context, boundAPIResourceSchema *kubebindv1alpha2.BoundAPIResourceSchemaApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	if boundAPIResourceSchema == nil {
		return nil, fmt.Errorf("boundAPIResourceSchema provided to Apply must not be nil")
	}
	data, err := json.Marshal(boundAPIResourceSchema)
	if err != nil {
		return nil, err
	}
	name := boundAPIResourceSchema.Name
	if name == nil {
		return nil, fmt.Errorf("boundAPIResourceSchema.Name must be provided to Apply")
	}
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(boundapiresourceschemasResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeBoundAPIResourceSchemas) ApplyStatus(ctx context.Context, boundAPIResourceSchema *kubebindv1alpha2.BoundAPIResourceSchemaApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha2.BoundAPIResourceSchema, err error) {
	if boundAPIResourceSchema == nil {
		return nil, fmt.Errorf("boundAPIResourceSchema provided to Apply must not be nil")
	}
	data, err := json.Marshal(boundAPIResourceSchema)
	if err != nil {
		return nil, err
	}
	name := boundAPIResourceSchema.Name
	if name == nil {
		return nil, fmt.Errorf("boundAPIResourceSchema.Name must be provided to Apply")
	}
	emptyResult := &v1alpha2.BoundAPIResourceSchema{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(boundapiresourceschemasResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha2.BoundAPIResourceSchema), err
}
